name: covid-19
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - art=2016.06.05
  - bcftools
  - biopython=1.74
  - cairo
  - gofasta
  - ivar
  - minimap2
  - openjdk=11.0.8
  - pango
  - pip
  - python=3.7
  - samtools
  - seqtk
  - snakemake-minimal
  - weasyprint

  - pip:
    - pandas==1.0.1
    - biopython==1.74
    - git+https://github.com/cov-lineages/pangoLEARN.git
