name: report

channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - art=2016.06.05
  - cairo
  - ivar
  - minimap2
  - pango
  - samtools
  - seqtk
  - seqkit
  - openjdk
  - bcftools

  - python=3.7
  - pip

  # conda's pip installer does not install extras so these are specified
  # manually (under onecodex) a better solution would be able to install using
  # `pip` into the conda environment (what one would expect conda to do here)
  - pip:
    - biopython
    - pandas
    - altair
    - onecodex[all,reports]
    - notebook
    - nbconvert<6
    - WeasyPrint
    - altair_saver
